### ISSUE TITLE
Idea: Also be able to use the BLE Meater probes

### ISSUE THREAD

**Issue by frankhommers** [CapnBry/HeaterMeter#54]
I could possibly help figuring out the BLE protocol for https://meater.com/

**Comment by CapnBry** [comment]
I have one of these as well, and one of the users on the forums has a ~20 line Python script that can decode the values. However, I'm not going to include the entirety of Python in the firmware image just to run a 20 line script. If it was converted to a standalone executable of <100KB or so I'd be happy to make the changes to the HeaterMeter code to accept getting temperature data fed into it from the outside.

I'm going to close this issue though because I don't see that happening.
