### ISSUE TITLE
Temp Probe Graphs

### ISSUE THREAD

**Issue by CoffeeTronics** [CapnBry/HeaterMeter#55]
Hi, I have been reading over your repo and I was wondering where you obtained the probe temperature curves from?
I am using the Maverick ET-73. For fun I am trying to produce a lookup table and wanted to compare my results to see if they made sense.
Any pointers are greatly appreciated!

**Comment by CapnBry** [comment]
The ET-72/73 probe coefficients I use are curve fit from a PDF file that's floating around the internet that was allegedly were provided (faxed?) from Maverick with a table of temperatures and resistances for the thermistor they use. It's been a decade since I've seen that file though so I'm not sure where it can be found these days.

If you're just looking for a full dump of the curve of the temperature to 10-bit ADC reading, then maybe a test page I use to compare probes and resistances could help. You can find that at [HeaterMeter ADC Resolution](https://heatermeter.com/devel/adctherm/). If you have further questions about it then I'd invite you to post [on the forums](https://tvwbb.com/forums/heatermeter-diy-bbq-controller.85/) where you might get more responses or someone might even still have the original numbers that mine are fit to. The issue tracker here isn't really for Q and A.
