### ISSUE TITLE
msmtp configuration broken for PLAIN LOGIN authentication

### ISSUE THREAD

**Issue by jefw** [CapnBry/HeaterMeter#58]
When creating an SMTP Client configuration where:

- Requires authentication: on
- Enable TLS/SSL encryption: off

The admin interface creates /etc/msmtptc with "auth on".  This causes msmtp to fail with "cannot use a secure authentication method" error.

For SMTP servers supporting only PLAIN LOGIN, the appropriate directive is "auth login".  

@CapnBry - I have attached a lightly tested patch to openwrt/package/luci-app-msmtp/luasrc/model/cbi/admin_services/msmtp.lua, feel free to use if you wish or I can make a PR if you prefer.

[patch.txt](https://github.com/CapnBry/HeaterMeter/files/6281228/patch.txt)

**Comment by CapnBry** [comment]
Nice work finding this. I think I just looked at the `auth xxx` section of the msmtprc file and thought that "on" was the only option. Your patch overlooks that LOGIN and CRAM-MD5 are also valid auth options so instead of forcing it to PLAIN, I now just let the user select which auth mechanism they want (including "Auto" which is what the old version did).

**Comment by jefw** [comment]
That's the better solution, for sure.  I didn't really want to noodle with the UI, but an option list is surely more usable in the end.
